name: Weekly Release

on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Get new AppIDs since last release
        id: new-appids
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "")
          if [ -z "$LAST_TAG" ]; then
            find artworks -name index.html | awk -F'/' '{print $3}' | sort -u > new_app_ids.txt
          else
            git diff --name-status $LAST_TAG HEAD -- artworks/*/*/index.html | awk '$1=="A"{print $2}' | awk -F'/' '{print $3}' | sort -u > new_app_ids.txt
          fi
          cat new_app_ids.txt

      - name: Take screenshots
        run: node scripts/screenshot.js

      - name: Create zip
        run: |
          cd screenshots
          zip -r ../grid.zip grid

      - name: Set release date
        run: echo "RELEASE_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        
      - name: Format release notes
        run: |
          if [ -s new_app_ids.txt ]; then
            FORMATTED_IDS=$(while read id; do echo -n "[\`$id\`](https://steamdb.info/$id), "; done < new_app_ids.txt | sed 's/, $//')
            echo "FORMATTED_IDS<<EOF" >> $GITHUB_ENV
            echo "$FORMATTED_IDS" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "FORMATTED_IDS=No new AppIDs" >> $GITHUB_ENV
          fi
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.RELEASE_DATE }}"
          name: "v${{ env.RELEASE_DATE }}"
          body: |
            New artworks for the following games:
            ${{ env.FORMATTED_IDS }}
          files: grid.zip
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up temporary files
        if: always()
        run: |
          rm -f game_ids.txt new_app_ids.txt
          echo "Cleaned up temporary files"