name: Weekly Release

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Check for new AppIDs
        id: new-appids
        run: |
          if [ -s game_ids.txt ]; then
            echo "has_new=true" >> $GITHUB_OUTPUT
            cat game_ids.txt
          else
            echo "has_new=false" >> $GITHUB_OUTPUT
            echo "Nothing new yet."
          fi

      - name: Take screenshots
        run: node scripts/screenshot.js

      - name: Create zip
        run: |
          cd screenshots
          zip -r ../grid.zip grid

      - name: Set release date
        run: echo "RELEASE_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Format release notes
        run: |
          if [ -s game_ids.txt ]; then
            FORMATTED_IDS=$(while read id; do echo -n "[\`$id\`](https://steamdb.info/app/$id), "; done < game_ids.txt | sed 's/, $//')
            echo "FORMATTED_IDS<<EOF" >> $GITHUB_ENV
            echo "$FORMATTED_IDS" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "FORMATTED_IDS=No new AppIDs" >> $GITHUB_ENV
          fi

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.RELEASE_DATE }}"
          name: "v${{ env.RELEASE_DATE }}"
          body: |
            New artworks for the following games:
            ${{ env.FORMATTED_IDS }}
          files: grid.zip
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete game_ids.txt and commit
        if: always()
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          if [ -f game_ids.txt ]; then
            rm -f game_ids.txt
            git add game_ids.txt
            git commit -m "Clear game_ids.txt after release"
            git push
          fi
          rm -f new_app_ids.txt
          echo "Cleaned up and committed"
